news_fetch:
  template: |
    Please provide the {num_articles} most recent technology and AI news stories from the last 24 hours.
    Focus on breaking news and latest developments in:
    - AI/ML developments and breakthroughs
    - Tech industry news and trends
    - Major tech company announcements
    - Emerging technologies
    - Tech policy and regulation
    - Tech startup news and funding rounds
    - Tech market trends
    
    For each story, include:
    1. A clear headline
    2. A concise summary (2-3 sentences)
    3. The source (MUST be one of these specific outlets: The Verge, TechCrunch, Wired, MIT Technology Review, The New York Times, Financial Times, Nature, Science, Reuters, Bloomberg, CNBC, Wall Street Journal)
    4. The URL (MUST be a valid, working URL starting with https:// that links directly to the article on the source's website)
    5. Publication time (in ISO format with timezone)
    6. Category (e.g., AI/ML, Cloud Computing, Cybersecurity, Hardware, Software, Tech Policy, Funding)
    7. Importance score (0-1)
    8. Sentiment score (-1 to 1)
    9. Why it matters (a brief explanation of why this story is significant)
    
    CRITICAL REQUIREMENTS:
    - Each story MUST come from a different source from the list above
    - Each URL MUST be a real, working URL starting with https:// that points to the actual article
    - DO NOT include any story if you cannot find its actual URL
    - DO NOT make up or guess URLs
    - Only include stories from the last 24 hours
    - If you cannot find enough stories meeting these requirements, return fewer stories
    
    Format the response as a JSON array of articles. Ensure to include a mix of funding news, research breakthroughs, and general tech news.
  max_tokens: 2500
  temperature: 0.7
  model: sonar

breaking_news:
  template: |
    Please provide the {num_articles} most recent breaking technology and AI news stories from the last 24 hours.
    Focus on urgent, time-sensitive developments in:
    - AI/ML breakthroughs and announcements
    - Major tech company news and announcements
    - Tech industry breaking news
    - Emerging technology developments
    - Tech policy and regulatory changes
    - Tech startup funding and acquisitions
    - Market-moving tech news
    
    For each story, include:
    1. A clear headline
    2. A concise summary (2-3 sentences)
    3. The source (MUST be one of these specific outlets: The Verge, TechCrunch, Wired, MIT Technology Review, The New York Times, Financial Times, Nature, Science, Reuters, Bloomberg, CNBC, Wall Street Journal)
    4. The URL (MUST be a valid, working URL starting with https:// that links directly to the article on the source's website)
    5. Publication time (in ISO format with timezone)
    6. Category (e.g., AI/ML, Cloud Computing, Cybersecurity, Hardware, Software, Tech Policy, Funding)
    7. Importance score (0-1)
    8. Sentiment score (-1 to 1)
    9. Why it matters (a brief explanation of why this story is significant)
    
    CRITICAL REQUIREMENTS:
    - Each story MUST come from a different source from the list above
    - Each URL MUST be a real, working URL starting with https:// that points to the actual article
    - DO NOT include any story if you cannot find its actual URL
    - DO NOT make up or guess URLs
    - Only include stories from the last 24 hours
    - Focus on breaking, urgent news
    - If you cannot find enough stories meeting these requirements, return fewer stories
    
    Format the response as a JSON array of articles.
  max_tokens: 2500
  temperature: 0.7
  model: sonar

funding_news:
  template: |
    Please provide the {num_articles} most recent technology funding and M&A news stories from the last 24 hours.
    Focus on:
    - Startup funding rounds and valuations
    - Venture capital investments
    - Mergers and acquisitions
    - IPO announcements
    - Corporate investments in tech
    - Tech company financial news
    
    For each story, include:
    1. A clear headline
    2. A concise summary (2-3 sentences)
    3. The source (MUST be one of these specific outlets: The Verge, TechCrunch, Wired, MIT Technology Review, The New York Times, Financial Times, Nature, Science, Reuters, Bloomberg, CNBC, Wall Street Journal)
    4. The URL (MUST be a valid, working URL starting with https:// that links directly to the article on the source's website)
    5. Publication time (in ISO format with timezone)
    6. Category (e.g., Funding, M&A, IPO, Investment)
    7. Importance score (0-1)
    8. Sentiment score (-1 to 1)
    9. Why it matters (a brief explanation of why this story is significant)
    
    CRITICAL REQUIREMENTS:
    - Each story MUST come from a different source from the list above
    - Each URL MUST be a real, working URL starting with https:// that points to the actual article
    - DO NOT include any story if you cannot find its actual URL
    - DO NOT make up or guess URLs
    - Only include stories from the last 24 hours
    - Focus specifically on funding, M&A, and financial news
    - If you cannot find enough stories meeting these requirements, return fewer stories
    
    Format the response as a JSON array of articles.
  max_tokens: 2500
  temperature: 0.7
  model: sonar

research_news:
  template: |
    Please provide the {num_articles} most recent technology research and breakthrough news stories from the last 24 hours.
    Focus on:
    - AI/ML research breakthroughs
    - New technology developments
    - Scientific discoveries in tech
    - Research papers and studies
    - Technical innovations
    - Academic research in technology
    
    For each story, include:
    1. A clear headline
    2. A concise summary (2-3 sentences)
    3. The source (MUST be one of these specific outlets: The Verge, TechCrunch, Wired, MIT Technology Review, The New York Times, Financial Times, Nature, Science, Reuters, Bloomberg, CNBC, Wall Street Journal)
    4. The URL (MUST be a valid, working URL starting with https:// that links directly to the article on the source's website)
    5. Publication time (in ISO format with timezone)
    6. Category (e.g., Research, AI/ML, Innovation, Science)
    7. Importance score (0-1)
    8. Sentiment score (-1 to 1)
    9. Why it matters (a brief explanation of why this story is significant)
    
    CRITICAL REQUIREMENTS:
    - Each story MUST come from a different source from the list above
    - Each URL MUST be a real, working URL starting with https:// that points to the actual article
    - DO NOT include any story if you cannot find its actual URL
    - DO NOT make up or guess URLs
    - Only include stories from the last 24 hours
    - Focus specifically on research, breakthroughs, and technical innovations
    - If you cannot find enough stories meeting these requirements, return fewer stories
    
    Format the response as a JSON array of articles.
  max_tokens: 2500
  temperature: 0.7
  model: sonar

top_stories:
  template: |
    Please provide the {num_articles} most significant technology and AI news stories from the last 7 days.
    Focus on the most impactful and important developments in:
    - AI/ML developments and breakthroughs
    - Tech industry news and trends
    - Major tech company announcements
    - Emerging technologies
    - Tech policy and regulation
    - Tech startup news and funding rounds
    - Tech market trends
    
    For each story, include:
    1. A clear headline
    2. A concise summary (2-3 sentences)
    3. The source (MUST be one of these specific outlets: The Verge, TechCrunch, Wired, MIT Technology Review, The New York Times, Financial Times, Nature, Science, Reuters, Bloomberg, CNBC, Wall Street Journal)
    4. The URL (MUST be a valid, working URL starting with https:// that links directly to the article on the source's website)
    5. Publication time (in ISO format with timezone)
    6. Category (e.g., AI/ML, Cloud Computing, Cybersecurity, Hardware, Software, Tech Policy, Funding)
    7. Importance score (0-1)
    8. Sentiment score (-1 to 1)
    9. Why it matters (a brief explanation of why this story is significant)
    
    CRITICAL REQUIREMENTS:
    - Each story MUST come from a different source from the list above
    - Each URL MUST be a real, working URL starting with https:// that points to the actual article
    - DO NOT include any story if you cannot find its actual URL
    - DO NOT make up or guess URLs
    - Focus on the most significant stories from the past 7 days
    - If you cannot find enough stories meeting these requirements, return fewer stories
    
    Format the response as a JSON array of articles. Ensure to include a mix of funding news, research breakthroughs, and general tech news.
  max_tokens: 2500
  temperature: 0.7
  model: sonar

news_analysis:
  template: |
    Analyze these technology and AI news articles and identify:
    1. Major themes and trends in tech and AI
    2. Most significant technological developments
    3. Potential connections between different tech stories
    4. Overall sentiment of the tech industry
    5. Emerging patterns in AI development
    6. Key players and their strategic moves
    7. Potential impact on the tech industry
    
    Articles:
    {articles_text}
  max_tokens: 2000
  temperature: 0.7
  model: sonar

ai_trends_summary:
  template: |
    Provide a concise, executive-level summary of the most critical AI developments from the past week. Focus on what matters for AI leaders, executives, and decision-makers.

    IMPORTANT: Include citations for all sources in the format [1] Source Name - Title (URL), [2] Source Name - Title (URL), etc. at the end of your response.

    Structure your response as follows:

    **Executive Summary** (2-3 sentences)
    Brief overview of the most significant AI developments and their business impact.

    **Key Strategic Developments** (3-4 bullet points)
    - Focus on major company moves, funding, acquisitions, and strategic partnerships
    - Highlight what this means for competitive positioning
    - Include specific implications for AI leaders

    **Action Items for AI Leaders** (3-4 bullet points)
    - Prioritize building or acquiring AI agent capabilities that can autonomously manage dynamic workflows to boost productivity and customer engagement
    - Accelerate development of multimodal AI systems that can process and generate content across text, image, video, and audio formats
    - Invest in AI-powered customer experience platforms that can provide personalized, real-time interactions across all touchpoints
    - Develop comprehensive AI governance frameworks that balance innovation with responsible deployment and risk management

    **Bottom Line** (1-2 sentences)
    The most critical takeaway for AI leaders and decision-makers.

    **Citations:**
    [1] Source Name - Title (URL)
    [2] Source Name - Title (URL)
    [3] Source Name - Title (URL)
    [4] Source Name - Title (URL)

executive_action_items:
  template: |
    Based on the latest AI industry developments, provide exactly 3 specific, actionable strategic items for AI leaders and executives to prioritize. Focus on the most impactful actions they can take to stay competitive and drive value.

    IMPORTANT: Include citations for all sources in the format [1] Source Name - Title (URL), [2] Source Name - Title (URL), etc. at the end of your response. Prioritize high-quality sources like TechCrunch, The Verge, MIT Technology Review, Nature, Science, Financial Times, etc.

    Structure your response as follows:

    **Strategic Action Items for AI Leaders:**

    1. [Specific action item with reference to relevant development] [citation number]
    2. [Specific action item with reference to relevant development] [citation number]
    3. [Specific action item with reference to relevant development] [citation number]

    **Citations:**
    [1] Source Name - Title (URL)
    [2] Source Name - Title (URL)
    [3] Source Name - Title (URL) 